/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package peminjamanloker;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;

/**
 *
 * @author Akn
 */
public class menu extends javax.swing.JFrame {

    private int loker_selected = 0;
    private int txt_nama_not_empty = 0;
    private int txt_no_tlp_not_empty = 0;
    
    private ArrayList<String> loker = new ArrayList<>();
    
    private Connection conn;
    private final String driverClass = "com.mysql.cj.jdbc.Driver";
    private final String url = "jdbc:mysql://localhost:3306/peminjaman_loker?";
    private final String user = "root";
    private final String pass = "";
        
    public void readDB() throws ClassNotFoundException, SQLException{
        Class.forName(driverClass);
        conn = DriverManager.getConnection(url, user, pass);
    }
    
    /**
     * Creates new form menu
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public menu() throws ClassNotFoundException, SQLException {
        initComponents();
        
        checkInput();  
        
        System.out.println("Connecting to database...");

//        try (Connection conn = DriverManager.getConnection(driver, user, pass)) {
//            System.out.println("Database connected!");
//        } catch (SQLException e) {
//            throw new IllegalStateException("Cannot connect the database!", e);
//        }
        
        ambilDataDariDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tglBtnLoker1 = new javax.swing.JToggleButton();
        tglBtnLoker2 = new javax.swing.JToggleButton();
        tglBtnLoker3 = new javax.swing.JToggleButton();
        tglBtnLoker4 = new javax.swing.JToggleButton();
        tglBtnLoker5 = new javax.swing.JToggleButton();
        tglBtnLoker6 = new javax.swing.JToggleButton();
        tglBtnLoker7 = new javax.swing.JToggleButton();
        tglBtnLoker8 = new javax.swing.JToggleButton();
        lbl1 = new javax.swing.JLabel();
        txtNamaPeminjam = new javax.swing.JTextField();
        lbl2 = new javax.swing.JLabel();
        txtNoTlp = new javax.swing.JTextField();
        btnLanjut = new javax.swing.JButton();
        btnPengembalian = new javax.swing.JButton();
        btnResetLoker = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Peminjaman Loker");
        setName("frmMenu"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tglBtnLoker1.setText("1");
        tglBtnLoker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnLoker1ActionPerformed(evt);
            }
        });
        getContentPane().add(tglBtnLoker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 100, 100));

        tglBtnLoker2.setText("2");
        tglBtnLoker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnLoker2ActionPerformed(evt);
            }
        });
        getContentPane().add(tglBtnLoker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 100, 100));

        tglBtnLoker3.setText("3");
        tglBtnLoker3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnLoker3ActionPerformed(evt);
            }
        });
        getContentPane().add(tglBtnLoker3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 100, 100));

        tglBtnLoker4.setText("4");
        tglBtnLoker4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnLoker4ActionPerformed(evt);
            }
        });
        getContentPane().add(tglBtnLoker4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 100, 100));

        tglBtnLoker5.setText("5");
        tglBtnLoker5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnLoker5ActionPerformed(evt);
            }
        });
        getContentPane().add(tglBtnLoker5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 100, 100));

        tglBtnLoker6.setText("6");
        tglBtnLoker6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnLoker6ActionPerformed(evt);
            }
        });
        getContentPane().add(tglBtnLoker6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 100, 100));

        tglBtnLoker7.setText("7");
        tglBtnLoker7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnLoker7ActionPerformed(evt);
            }
        });
        getContentPane().add(tglBtnLoker7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 100, 100));

        tglBtnLoker8.setText("8");
        tglBtnLoker8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnLoker8ActionPerformed(evt);
            }
        });
        getContentPane().add(tglBtnLoker8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 100, 100));

        lbl1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl1.setText("Nama Peminjam");
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        txtNamaPeminjam.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNamaPeminjam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamaPeminjamKeyReleased(evt);
            }
        });
        getContentPane().add(txtNamaPeminjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 400, -1));

        lbl2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl2.setText("Nomor Telepon");
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        txtNoTlp.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNoTlp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNoTlpKeyReleased(evt);
            }
        });
        getContentPane().add(txtNoTlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 400, -1));

        btnLanjut.setText("Lanjut");
        btnLanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanjutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLanjut, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 80, 30));

        btnPengembalian.setLabel("Pengembalian");
        btnPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengembalianActionPerformed(evt);
            }
        });
        getContentPane().add(btnPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, 30));

        btnResetLoker.setText("Reset Loker");
        btnResetLoker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetLokerActionPerformed(evt);
            }
        });
        getContentPane().add(btnResetLoker, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, 30));

        setSize(new java.awt.Dimension(718, 559));
    }// </editor-fold>//GEN-END:initComponents

    private void ambilDataDariDatabase() {
        // ngambil data status loker dari database
        try {
            conn = DriverManager.getConnection(url, user, pass);
            Statement stm = conn.createStatement();
            ResultSet rs = stm.executeQuery("SELECT * from loker");
            
            while(rs.next()){
                int id_loker = rs.getInt("id_loker");
                int status = rs.getInt("status_loker");
                if(id_loker == 1 && status == 0){
                    tglBtnLoker1.setEnabled(false);
                } else if(id_loker == 2 && status == 0){
                    tglBtnLoker2.setEnabled(false);
                } else if(id_loker == 3 && status == 0){
                    tglBtnLoker3.setEnabled(false);
                }else if(id_loker == 4 && status == 0){
                    tglBtnLoker4.setEnabled(false);
                } else if(id_loker == 5 && status == 0){
                    tglBtnLoker5.setEnabled(false);
                } else if(id_loker == 6 && status == 0){
                    tglBtnLoker6.setEnabled(false);
                } else if(id_loker == 7 && status == 0){
                    tglBtnLoker7.setEnabled(false);
                } else if(id_loker == 8 && status == 0){
                    tglBtnLoker8.setEnabled(false);
                } 
//                System.out.println(id_loker + " | " +status);
            }
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
    }
    
    private void tglBtnLoker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnLoker1ActionPerformed
        // TODO add your handling code here:
        if(tglBtnLoker1.isSelected()){
            this.loker_selected += 1;
            this.loker.add("1");
        } else {
            this.loker_selected -= 1;
            this.loker.remove("1");
        }
        
//        if(this.loker_selected <= 0){
//            btnLanjut.setEnabled(false);
//        } else {
//            btnLanjut.setEnabled(true);
//        }
        
        checkInput();
    }//GEN-LAST:event_tglBtnLoker1ActionPerformed

    private void tglBtnLoker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnLoker2ActionPerformed
        // TODO add your handling code here:
        if(tglBtnLoker2.isSelected()){
            this.loker_selected += 1;
            this.loker.add("2");
        } else {
            this.loker_selected -= 1;
            this.loker.remove("2");
        }
        
        checkInput();
    }//GEN-LAST:event_tglBtnLoker2ActionPerformed

    private void tglBtnLoker3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnLoker3ActionPerformed
        // TODO add your handling code here:
        if(tglBtnLoker3.isSelected()){
            this.loker_selected += 1;
            this.loker.add("3");
        } else {
            this.loker_selected -= 1;
            this.loker.remove("3");
        }
        
        checkInput();
    }//GEN-LAST:event_tglBtnLoker3ActionPerformed

    private void tglBtnLoker4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnLoker4ActionPerformed
        // TODO add your handling code here:
        if(tglBtnLoker4.isSelected()){
            this.loker_selected += 1;
            this.loker.add("4");
        } else {
            this.loker_selected -= 1;
            this.loker.remove("4");
        }
        
        checkInput();
    }//GEN-LAST:event_tglBtnLoker4ActionPerformed

    private void tglBtnLoker5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnLoker5ActionPerformed
        // TODO add your handling code here:
        if(tglBtnLoker5.isSelected()){
            this.loker_selected += 1;
            this.loker.add("5");
        } else {
            this.loker_selected -= 1;
            this.loker.remove("5");
        }
        
        checkInput();
    }//GEN-LAST:event_tglBtnLoker5ActionPerformed

    private void tglBtnLoker6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnLoker6ActionPerformed
        // TODO add your handling code here:
        if(tglBtnLoker6.isSelected()){
            this.loker_selected += 1;
            this.loker.add("6");
        } else {
            this.loker_selected -= 1;
            this.loker.remove("6");
        }
        
        checkInput();
    }//GEN-LAST:event_tglBtnLoker6ActionPerformed

    private void tglBtnLoker7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnLoker7ActionPerformed
        // TODO add your handling code here:
        if(tglBtnLoker7.isSelected()){
            this.loker_selected += 1;
            this.loker.add("7");
        } else {
            this.loker_selected -= 1;
            this.loker.add("7");
        }
        
        checkInput();
    }//GEN-LAST:event_tglBtnLoker7ActionPerformed

    private void tglBtnLoker8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnLoker8ActionPerformed
        // TODO add your handling code here:
        if(tglBtnLoker8.isSelected()){
            this.loker_selected += 1;
            this.loker.add("8");
        } else {
            this.loker_selected -= 1;
            this.loker.add("8");
        }
        
        checkInput();
    }//GEN-LAST:event_tglBtnLoker8ActionPerformed

    private void txtNamaPeminjamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaPeminjamKeyReleased
        // TODO add your handling code here:
        if(txtNamaPeminjam.getText().length() > 0){
            this.txt_nama_not_empty = 1;
        } else {
            this.txt_nama_not_empty = 0;
        }
        
        checkInput();
    }//GEN-LAST:event_txtNamaPeminjamKeyReleased

    private void btnLanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutActionPerformed
      
        try {
            // TODO add your handling code here:
//        System.out.println(pisahLoker(this.loker));
//        System.out.println(txtNamaPeminjam.getText());
//        System.out.println(txtNoTlp.getText());
//        System.out.println(this.loker.size());

            new konfirmasi(txtNamaPeminjam.getText(), txtNoTlp.getText(), loker).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setVisible(false);
    }//GEN-LAST:event_btnLanjutActionPerformed

    private void txtNoTlpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoTlpKeyReleased
        // TODO add your handling code here:
        char input_key = evt.getKeyChar();
        
        // cuma bisa input angka
        if(!(Character.isDigit(input_key)) && input_key != KeyEvent.VK_BACK_SPACE && input_key != KeyEvent.VK_DELETE && input_key != KeyEvent.VK_ENTER) {
            JOptionPane.showMessageDialog(rootPane, "Tolong hanya masukkan angka.");
            Document doc = txtNoTlp.getDocument();
            
            // delete the wrong input
            try {
                doc.remove(doc.getLength() - 1, 1);
            } catch (BadLocationException ex) {
            }
        }
        
        if(txtNoTlp.getText().length() > 0){
            this.txt_no_tlp_not_empty = 1;
        } else {
            this.txt_no_tlp_not_empty = 0;
        }       
        
        checkInput();
    }//GEN-LAST:event_txtNoTlpKeyReleased

    private void btnPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengembalianActionPerformed
        try {
            // TODO add your handling code here:
            new pengembalian().setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnPengembalianActionPerformed

    private void btnResetLokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetLokerActionPerformed
        try {
            // TODO add your handling code here:
            conn = DriverManager.getConnection(url, user, pass);
            
            Statement stm = conn.createStatement();
            stm.executeUpdate("UPDATE loker, peminjaman SET status_loker = 1, status_peminjaman = 0; ");
            
            new menu().setVisible(true);
            this.dispose();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnResetLokerActionPerformed

    // Cek klo gkada yg kosong diinputan
    private void checkInput(){
        if(this.loker_selected > 0 && this.txt_nama_not_empty != 0 && this.txt_no_tlp_not_empty != 0) {
            btnLanjut.setEnabled(true);
        } else {
            btnLanjut.setEnabled(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new menu().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLanjut;
    private javax.swing.JButton btnPengembalian;
    private javax.swing.JButton btnResetLoker;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JToggleButton tglBtnLoker1;
    private javax.swing.JToggleButton tglBtnLoker2;
    private javax.swing.JToggleButton tglBtnLoker3;
    private javax.swing.JToggleButton tglBtnLoker4;
    private javax.swing.JToggleButton tglBtnLoker5;
    private javax.swing.JToggleButton tglBtnLoker6;
    private javax.swing.JToggleButton tglBtnLoker7;
    private javax.swing.JToggleButton tglBtnLoker8;
    private javax.swing.JTextField txtNamaPeminjam;
    private javax.swing.JTextField txtNoTlp;
    // End of variables declaration//GEN-END:variables
}
